### ISSUE TITLE
Windows open up on secondary screen

### ISSUE THREAD

**Issue by bytefish** [linuxmint/muffin#102]
I am having a dual screen setup with Linux Mint 13 with Cinnamon 1.4.0. The problem is, that new maximized Windows seem to randomly open up on the secondary screen or jump between both. A bugfix in Mutter seems to be related, that's why I am opening an issue in this bugtracker:
- https://bugzilla.gnome.org/show_bug.cgi?id=556696

According to other users, this also happens in recent Linux Mint 15 versions. Is the problem known or has been fixed? I can reproduce the problem on Linux Mint 13 with the following simple steps: 
- Primary screen is on the right
- Start Google Chrome (or any other program probably) maximized on the (right side) primary screen
- Open a new Google Chrome Window, for example with `Ctrl + N`
- Start Typing a URL and ...
- The new Google Chrome Window jumps to the (left side) secondary screen

There has been quite a lot discussion on a very similar (if not same) problem in the mutter bugtracker, the patch they applied to [window.c](https://github.com/linuxmint/muffin/blob/master/src/core/window.c) is given at:
- https://bug556696.bugzilla-attachments.gnome.org/attachment.cgi?id=229686

This ticket is probably a duplicate of #43, though it is not related to Nemo or any specific program in my case.

**Comment by sixtyfive** [comment]
Any info on what Cinnamon release the fix will be in? 2.6.11doesn't seem to have it yet.

**Comment by JosephMcc** [comment]
This fix was merged almost 2 years ago. It's been in Cinnamon for a long time.

**Comment by sixtyfive** [comment]
Interesting, so why do most new windows still open on the secondary screen when it's left of the primary screen?

**Comment by JosephMcc** [comment]
Does it only happen with certain applications? Some apps seem to remember the last size and position they were at. How are your panels set up? Do you use panels on both monitors? What I normally have is a panel on both monitors with a panel launcher applet on each. The applet contains the apps I most commonly use on each monitor and they always seem to open on the proper one.

**Comment by sixtyfive** [comment]
Hi Joseph!

Of course there are some especially bad boys (Evince comes to mind whose maintainers I sometimes have fear of developing phantasies of violence against) but in general any application might open on the left screen.

I use one panel which correctly sits on the main monitor. So when the laptop is on its own it sits on the laptop screen and when it's docked the panel moves to the external monitor. I would have thought my use case to be rather simple, because I just want everything to always open on the main monitor and if I want something on the secondary monitor I'll have to move it there myself...
