### ISSUE TITLE
Black glitches after connecting monitor

### ISSUE THREAD

**Issue by germanfr** [linuxmint/muffin#542]
```
 * Cinnamon version 3.8.4
 * Distribution - Manjaro
 * Graphics hardware and driver used: Intel Corporation Haswell-ULT Integrated Graphics Controller
 * 64 bit
 ```

**Issue**
After connecting an external monitor (via VGA in my case), Cinnamon menus and windows get black glitches around (see the screenshot).

**Steps to reproduce**
Connect a monitor when Cinnamon is already running.
Drag a window, open a cinnamon menu or move the cursor over a menu, a window, panel applets, etc. (trigger redraws).

**Other information**
Restarting Cinnamon solves the issue.
It only happens in the newly connected monitor, not in the primary one. The dragged window must be entirely in the newly connected monitor for glitches to appear.

Glitches don't stay, they flicker only with some redraws (not 100% of the times but ~70%).

I couldn't take a screenshot because it seems to clear the glitches. I took a photo.
![screenshot](https://user-images.githubusercontent.com/10391266/41652260-d9c5fca0-7482-11e8-957a-3d91d233621a.jpg)

**Comment by tdebatty** [comment]
+1
cinnamon 4.2.4
kernel 4.15.0-70-generic
i915 driver
Lenovo T490s (Intel Core i7 Whiskey Lake and Intel graphics UHD 620)

**Comment by gobozov** [comment]
Same here. Thinkpad T460 (Intel 520 graphics) + 4k monitor. Linux Mint 19.3, i915 driver, 5.0.0-37-generic, Cinnamon 4.4.5

**Comment by zculek** [comment]
I had the same issue with Debian Buster + Cinnamon, really annoying, and since I saw a lot of people having this issue while searching for a solution, here's a way how to deal with it until this bug is fixed.

The issue looks to be related to Cinnamon Settings Daemon - xrandr plugin which is automatically started after logging in. Just disable it from Startup Applications and it will (or should) resolve this annoying problem/bug.

I am not sure what exactly is this pluggin for nor what it does, as there's no much information about it, but it seems I can live without it just fine, at least until this bug is fixed.

**Comment by Sraw** [comment]
I've confirmed that use `ctrl+atl+esc` to restart the cinnamon after logging in can solve this problem. 

Then it is strange, if just a restarting can solve the problem, we should be able to permanently solve it. Any updates about this issue?

**Comment by zaemiel** [comment]
> It's seems to get only this problem when i plugged the screen after my computer is already booted, not when is plugged-in before i power on. Anyone else can perform confirm ?

Yes, I can confirm. The glitches gone after reboot with two monitors plugged-in.
(Mint 19.3, Cinnamon 4.4.8)

**Comment by zaemiel** [comment]
> It's seems to get only this problem when i plugged the screen after my computer is already booted, not when is plugged-in before i power on. Anyone else can perform confirm ?

Yes, I can confirm. The glitches gone after reboot with two monitors plugged-in.
(Mint 19.3, Cinnamon 4.4.8)

**Comment by dullroar** [comment]
Can confirm on Dell Vostro laptop with external monitor plugged in, the "glitches" occur mostly on the main laptop screen (1920x1080), not the external monitor (1280x1024). Restarting Cinnamon seems to fix it. Here is some system info:
```
~$ inxi -SGxc 0
System:
  Host: MySystem Kernel: 5.3.0-28-generic x86_64 bits: 64 compiler: gcc 
  v: 7.4.0 Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia 
  base: Ubuntu 18.04 bionic 
Graphics:
  Device-1: Intel vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz, 1280x1024~60Hz 
  OpenGL: renderer: Mesa DRI Intel UHD Graphics (Whiskey Lake 3x8 GT2) 
  v: 4.5 Mesa 19.2.8 direct render: Yes 
```

**Comment by areographe** [comment]
Just installed Cinnamon on my Thinkpad X1 Carbon 4th generation, which has a mini DisplayPort and an HDMI output, running Manjaro. Haven't tried HDMI but using an ASUS PB278Q monitor connected with a mini DisplayPort to Displayport cable, I'm seeing the flickering windows, thick black borders, and general glitches.

Chromium seems particularly affected, as does the 'dock' app Plank.

`System:`
`    Host: luke-thinkpad Kernel: 5.4.18-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: Cinnamon 4.4.8 
           Distro: Manjaro Linux `
`Graphics:`  
`Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.7 driver: intel unloaded: modesetting resolution: 1920x1080~60Hz, 2560x1440~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2) v: 4.6 Mesa 19.3.4 direct render: Yes 
`

**Comment by tmanok** [comment]
I've been running Linux Mint on a T440s since Linux Mint Cinnamon 19.0 and with both (VGA + HDMI) and (VGA+DVI) as my external monitors, I get tons of glitches. Eliminated window-border glitches by adding a window frame of 1px to my box-shadows in ~/.config/gtk-3.0/gtk.css but I'm still experiencing wallpaper/desktop black boxes appearing randomly after connecting my dual monitors- the issue persists when I unplug them and normally stops after a reboot without monitors. 

My Linux Mint 19.1 through 19.3 machine at home experiences the same problems with a single HDMI TV connection. Similar problems on my other Thinkpads, but only when used with projectors and external video on rare occassion. I've also seen the problem with my OLD eMachines, Acers, and Asus'. Some of which are running single and dual core AMD CPUs from eons ago. 

None of these machines mentioned have graphics cards- Intel i5 3rd-8th Gens or super old AMDs only. Thanks.

**Comment by bonaccolto90** [comment]
I had the same problem on Manjaro and found a solution!
Basically you have to install xf86-video-intel if you're using an intel cpu (probably xf86-video-ati or xf86-video-amdgpu will work with amd cpu too, idk) and after a reboot, the problem is solved... tryed multyple times to do the glitch and its gone!

(Sorry if i wrote some words wrong, english is not my first language)

**Comment by LirisFR** [comment]
same problem


![gbccffcj9km21](https://user-images.githubusercontent.com/62543786/77305629-abe6b680-6cf6-11ea-9374-3ab65e78d598.gif)

**Comment by gvsa123** [comment]
> I've confirmed that use `ctrl+atl+esc` to restart the cinnamon after logging in can solve this problem.
> 
> Then it is strange, if just a restarting can solve the problem, we should be able to permanently solve it. Any updates about this issue?

I can confirm this on my system as well:
`System:    Host: P50 Kernel: 5.3.0-45-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 Desktop: Cinnamon 4.4.8 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Graphics:  Device-1: Intel HD Graphics 530 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA GM107GLM [Quadro M2000M] vendor: Lenovo driver: nouveau v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.5 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2) v: 4.5 Mesa 19.2.8 direct render: Yes `

Issue happens to me when I don't logout when docking. Ctrl+Alt+Esc worked.

**Comment by velaar** [comment]
I can cnofirm this bug on ArchLinux (current as of today)  UHD630 + GTX 1650

**Comment by carsteneu** [comment]
I came across the same problem with 2 external monitors... really annoying... but that easy to fix.

Got the solution from here:
http://www.webupd8.org/2015/11/fix-large-black-borders-around-header.html

In Short:
> To fix the large black borders bug
> open ~/.config/gtk-3.0/gtk.css (create the ~/.config/gtk-3.0 folder if it doesn't exist) with a text editor.

>> mkdir -p ~/.config/gtk-3.0
>gedit ~/.config/gtk-3.0/gtk.css

> and in this file, add the following:

>> .window-frame {
box-shadow: none;
margin: 1px;
}

>This forces any theme you use to have a 1 pixel border. You can use any value you want - for > instance, use "0" for borderless windows.

It worked like a charm - logout -> login and it was finally gone!

**Comment by clefebvre** [comment]
The CSS solution doesn't work here (on intel). I can reproduce the black (or white with muffin itself) boxes with or without the CSS styles above.

**Comment by Sraw** [comment]
So do I, this CSS solution doesn't work at all.

**Comment by clefebvre** [comment]
Good news!! @itzexor found a fix for this :) I can confirm it solves the issue here on Intel, on a box where I could reproduce the problem 100%.
