### ISSUE TITLE
Cinnamon crashes when launching applications that start out in full screen mode

### ISSUE THREAD

**Issue by ME4595** [linuxmint/muffin#592]
* muffin version: 5.0.1-3 (Manjaro package based on commit 23b345f2250d4e9d60e5facde1d5b1517391c8f2)
 * Distribution - Manjaro (Stable branch)
 * Graphics hardware and driver used:
  Device-1: NVIDIA GA104 [GeForce RTX 3070] vendor: ZOTAC driver: nvidia 
  v: 470.42.01 alternate: nouveau,nvidia_drm bus-ID: 2b:00.0 
The issue also occurred on driver version 465.xx
 * 64 bit

**Issue**
When launching applications that start out in full screen, the mouse cursor starts twitching and Cinnamon becomes unresponsive. Depending on the application that was tried to open, the app either crashes and Cinnamon goes into fallback mode and allows me to restart it using the fallback mode message dialogue, or it completely freezes and I have to kill the application I tried to open in TTY.
Cinnamon works normally after restarting it from fallback mode or closing the app using TTY.

**Steps to reproduce**
Start an application that starts out in full screen mode

**Expected behaviour**
Cinnamon does not crash and the application starts in full screen.

**Other information**
I have narrowed down the error to this commit 610d60d953cb1bfcc4b6a1aa61997f5d8234a90f, it does not occur when downgrading muffin to a version older than this commit

When running the app starting out in full screen using the terminal, I get the following error message:
```
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x[some number]
Serial number of failed request: [some number]
Current serial number in output stream: [some number]
```

**Comment by mtwebster** [comment]
What program(s)? I can't reproduce this with gnome-terminal or glxgears.

**Comment by ME4595** [comment]
I have reproduced the error with the games Muck, Factorio, Kerbal Space Program and Terraria. (The first one is free on Steam, the other ones unfortunately cost money.) I had the error occur both on games from Steam as well as standalone ones, so it is not limited to Steam. All of them work fine when downgrading muffin to the version before the commit I mentioned and start making problems again after updating back to the latest version.
I have also tried glxgears on my setup now (and Super Tux Kart), and both work fine for me even using the latest version of muffin.

**Comment by dknight-bg** [comment]
Same problem 
Manjaro Stable , muffin 5.0.1-3

**Comment by mtwebster** [comment]
Hi is this in your normal distro release or are you guys on some sort of daily or testing builds? The offending commit isn't in an 'official' release yet. I would say that unless you are encountering the issue that that commit fixes, you should just run plain 5.0.1

I regardless, I appreciate the beta testing :)

I've reproduced this with Muck, and have a partial fix, but still working on it.

Thanks

**Comment by ME4595** [comment]
Hi,

this 5.0.1-3 version is in the official stable branch of the Manjaro repos.

Thanks for helping us!

**Comment by markusdresch** [comment]
I'm on Cinnamon 5.0.4 (Manjaro DISTRIB_RELEASE=21.1.0, kernel 5.13.1-3) and I have the same issue with any application/game that starts in full screen.

**Comment by v4Lo** [comment]
> only did official updates, not sure why the 5.0.1-3 is mentioned as official. any way to downgrade apart from timeshift?

Thanks to this commit
https://gitlab.manjaro.org/packages/community/cinnamon/muffin/-/commit/dd226088a2566f989aa39f1386b50ce29457ddcc

Manjaro now builds from master head rather than muffin stable releases. Just build the official arch package, which still does the sane thing. If you don't have the 5.0.1-1 package in cache, so that the tool called downgrade (pacman -S downgrade) works you can still install asp from aur, then "asp checkout muffin", "makepkg" in the trunk folder, pacman -U the package file it and done. Don't upgrade muffin until a Manjaro releases a package that fixes the issue.

It's unfortunate that Manjaro forums point at upstream without looking at what the Manjaro repositories / maintainer did first. The issue with Manjaro Cinnamon having this bug is on them, not on Muffin.

**Comment by markusdresch** [comment]
thanks a lot. i did try the downgrade route yesterday, but it seemed to only affect the single package without deps resulting in an error when starting cinnamon. will look into asp later, thank you again for the input.

and sorry for interrupting this thread, but wanted to share that the same problem occurs with the version i'm on.

**Comment by mtwebster** [comment]
Ok I think I've got this fixed now in git master. It actually seems to behave slightly better - muck didn't seem to like my 4k monitor (scaled to 1920x1080) before - it would only show 1/4 of the game window, now it starts out properly.

Please let me know if someone can confirm the fix - I'll re-open the issue if not.

**Comment by ME4595** [comment]
Hi,
the fix works on my setup. Thank you for solving that issue!

**Comment by sobrus** [comment]
I've just came across the same problem with Manjaro on my RX570 with Kerbal Space Program and Shadow Of Tomb Raider.
Thanks for fixing the issue! I can confirm that downgrading to Muffin 4.8 helps. KSP didn't want to start even in windowed mode, so I'm not sure if this really was only a full screen issue.
I didn't manage to build muffin binary from sources yet, so I can't confirm that the fix is working :(

**Comment by dknight-bg** [comment]
> Hi,
> the fix works on my setup. Thank you for solving that issue!

manjaro/muffin 5.0.1-5 fix the problem  
Thanks
