### ISSUE TITLE
Snapping no longer works

### ISSUE THREAD

**Issue by JackNWhite** [linuxmint/muffin#632]
```
 * muffin version: mutter 5.4.5
 * Distribution: Mint 21
 * GTX 770 / nVidia driver 470.141.03-0ubuntu0.22.04.1
 * 64b
 ```

**Issue**
Cinnamon's snapping facility (by default Ctrl+Left/Right/Up/DownArrow) no longer works. It has been removed from cinnamon-settings and I have traced it back to Muffin, which contained this:
```
src/org.cinnamon.muffin.gschema.xml.in:155:    <key name="snap-modifier" type="s">
```
...in version 5.0.0, but contains no mention of snap-modifier in v5.4.5

**Steps to reproduce**
- Install Linux Mint 21.
- Try to snap your windows with Ctrl+Left/Right/Up/DownArrow.

**Expected behaviour**
The current window snaps to the left/right/top/bottom.

**Other information**
There appears to be plenty of snapping-related code in there - in, for example, *clutter-flow-layout.c* and *clutter-snap-constraint.c*, but it is not exposed, or not exposed in the same as in the past.

**Comment by mtwebster** [comment]
Snapping was removed in 5.4. It would need to be reimplemented due to extensive changes in Muffin and we didn't feel it was a popular enough feature to warrant the significant effort it would require..

With the fact that tiling is a bit more capable now - resizing neighbor windows, auto-sizing to match existing tiled windows, and browsers having picture-in-picture we thought it was less useful as well.
