### ISSUE TITLE
Feature Loss - New Window Position: Mouse Pointer

### ISSUE THREAD

**Issue by Phx01** [linuxmint/muffin#648]
```
 * Distribution - Fedora 37
 * 64 bit
 ```

**Issue**
Feature Loss - New Window Position: Mouse Pointer
In Fedora 36 (and before) there was a feature for the placement of new windows under the mouse pointer.  For Fedora 37 this has been replaced by a blunt choice of "center new windows" (or not = automatic).

Personally I found this feature quite helpful since when a new window opens, your typical focus on screen is where the mouse pointer lingers.  Is there a possibility to bring it back?  If not, why has it been removed?  Did it disturb something else?

**Comment by dgrisby** [comment]
I have also just upgraded to Fedora 37 and very much miss this feature!

I contributed the feature in the first place: https://github.com/linuxmint/muffin/pull/117

Was there a very good reason for removing it?

**Comment by dgrisby** [comment]
I have looked into it, and the functionality was lost in https://github.com/linuxmint/muffin/commit/8599127fa99dc285426fd84c2f53ed0ae8d60d3c when there was a massive merge of changes from upstream mutter.

I have updated my original change so it works again. Will a PR that brings the functionality back be accepted?  If so, should I update cinnamon-settings to expose it?  At the moment, I have brought back the placement-mode setting, and muffin uses that instead of the center-new-windows setting, and you can choose between four placement modes in dconf-editor – automatic, center, pointer and manual.

cinnamon-settings still sets the center-new-windows setting, which no longer takes effect. I could do one of three things:

1. update cinnamon-settings to expose all four options
2. update cinnamon-settings to set the new setting, but only allow you to choose between automatic and center (which seems ugly to me)
3. make it so that muffin still looks at center-new-windows, and does that if it is true, and only uses pointer / manual from placement-mode if center-new-windows was false.

I would prefer option 1, but I'm not going to spend time doing it if another option is preferred, or if my whole PR would not be accepted.

**Comment by Phx01** [comment]
@dgrisby, it good to see that more people miss this feature.  Even better that you originally introduced it.  So, a big thanks for this feature in the first place and thanks again for even maintaining it!

Still being a bit unfamiliar with this platform (and I am not a programmer, but rather a system administrator), is there a way for me to test-drive your addition or would it require in-depth programmers skills to implement?

**Comment by dgrisby** [comment]
@Phx01, if you don't know how to build it from my PR, I'm not sure. I guess I could send you a built RPM.

**Comment by Phx01** [comment]
@dgrisby , don't get me wrong.  I am all down to get my hands dirty (and eager to learn).  However, as a "simple" scripter, I would possibly need directions.  If, on the other side, you can (and want) to create a built RPM, I am also happy.

Of course, ideally it would be officially merged and integrated into F37.  Though seeing this thread without a sign of the Muffin maintainer(s) for several days, it may take some more time before this happens.

**Comment by dgrisby** [comment]
@Phx01, if you want it fixed in Fedora 37, I think you should probably raise a bug in the Fedora bug tracker at https://bugzilla.redhat.com/ and point it to this github issue.

**Comment by leigh123linux** [comment]
@dgrisby I don't like adding non-upstream features.

@mtwebster  Is this likely to get merged?

**Comment by dgrisby** [comment]
@leigh123linux, I wasn't suggesting putting it in Fedora if it isn't accepted upstream here, but I thought it might go into Fedora sooner if it was raised there as well. I may be wrong about that.

**Comment by mtwebster** [comment]
Yes I think so but it's probably too late for 5.6.
